In [28]:
import pandas as pd

In [29]:
df = pd.read_csv("aac_intakes.csv")
df.head()

,age_upon_intake,animal_id,animal_type,breed,color,datetime,datetime2,found_location,intake_condition,intake_type,name,sex_upon_intake
0,8 years,A706918,Dog,English Springer Spaniel,White/Liver,2015-07-05T12:59:00.000,2015-07-05T12:59:00.000,9409 Bluegrass Dr in Austin (TX),Normal,Stray,Belle,Spayed Female
1,11 months,A724273,Dog,Basenji Mix,Sable/White,2016-04-14T18:43:00.000,2016-04-14T18:43:00.000,2818 Palomino Trail in Austin (TX),Normal,Stray,Runster,Intact Male
2,4 weeks,A665644,Cat,Domestic Shorthair Mix,Calico,2013-10-21T07:59:00.000,2013-10-21T07:59:00.000,Austin (TX),Sick,Stray,NaN,Intact Female
3,4 years,A682524,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2014-06-29T10:38:00.000,2014-06-29T10:38:00.000,800 Grove Blvd in Austin (TX),Normal,Stray,Rio,Neutered Male
4,2 years,A743852,Dog,Labrador Retriever Mix,Chocolate,2017-02-18T12:46:00.000,2017-02-18T12:46:00.000,Austin (TX),Normal,Owner Surrender,Odin,Neutered Male

In [30]:
df = pd.read_csv("aac_outcomes.csv")
df.head()

,age_upon_outcome,animal_id,animal_type,breed,color,date_of_birth,datetime,monthyear,name,outcome_subtype,outcome_type,sex_upon_outcome
0,2 weeks,A684346,Cat,Domestic Shorthair Mix,Orange Tabby,2014-07-07T00:00:00,2014-07-22T16:04:00,2014-07-22T16:04:00,NaN,Partner,Transfer,Intact Male
1,1 year,A666430,Dog,Beagle Mix,White/Brown,2012-11-06T00:00:00,2013-11-07T11:47:00,2013-11-07T11:47:00,Lucy,Partner,Transfer,Spayed Female
2,1 year,A675708,Dog,Pit Bull,Blue/White,2013-03-31T00:00:00,2014-06-03T14:20:00,2014-06-03T14:20:00,*Johnny,NaN,Adoption,Neutered Male
3,9 years,A680386,Dog,Miniature Schnauzer Mix,White,2005-06-02T00:00:00,2014-06-15T15:50:00,2014-06-15T15:50:00,Monday,Partner,Transfer,Neutered Male
4,5 months,A683115,Other,Bat Mix,Brown,2014-01-07T00:00:00,2014-07-07T14:04:00,2014-07-07T14:04:00,NaN,Rabies Risk,Euthanasia,Unknown

In [31]:
df = pd.read_csv("aac_intakes_outcomes.csv") #merger of both the above datsets

In [32]:
df.head()

,age_upon_outcome,animal_id_outcome,date_of_birth,outcome_subtype,outcome_type,sex_upon_outcome,age_upon_outcome_(days),age_upon_outcome_(years),age_upon_outcome_age_group,outcome_datetime,...,age_upon_intake_age_group,intake_datetime,intake_month,intake_year,intake_monthyear,intake_weekday,intake_hour,intake_number,time_in_shelter,time_in_shelter_days
0,10 years,A006100,2007-07-09 00:00:00,NaN,Return to Owner,Neutered Male,3650,10.0,"(7.5, 10.0]",2017-12-07 14:07:00,...,"(7.5, 10.0]",2017-12-07 00:00:00,12,2017,2017-12,Thursday,14,1.0,0 days 14:07:00.000000000,0.588194
1,7 years,A006100,2007-07-09 00:00:00,NaN,Return to Owner,Neutered Male,2555,7.0,"(5.0, 7.5]",2014-12-20 16:35:00,...,"(5.0, 7.5]",2014-12-19 10:21:00,12,2014,2014-12,Friday,10,2.0,1 days 06:14:00.000000000,1.259722
2,6 years,A006100,2007-07-09 00:00:00,NaN,Return to Owner,Neutered Male,2190,6.0,"(5.0, 7.5]",2014-03-08 17:10:00,...,"(5.0, 7.5]",2014-03-07 14:26:00,3,2014,2014-03,Friday,14,3.0,1 days 02:44:00.000000000,1.113889
3,10 years,A047759,2004-04-02 00:00:00,Partner,Transfer,Neutered Male,3650,10.0,"(7.5, 10.0]",2014-04-07 15:12:00,...,"(7.5, 10.0]",2014-04-02 15:55:00,4,2014,2014-04,Wednesday,15,1.0,4 days 23:17:00.000000000,4.970139
4,16 years,A134067,1997-10-16 00:00:00,NaN,Return to Owner,Neutered Male,5840,16.0,"(15.0, 17.5]",2013-11-16 11:54:00,...,"(15.0, 17.5]",2013-11-16 09:02:00,11,2013,2013-11,Saturday,9,1.0,0 days 02:52:00.000000000,0.119444

In [33]:
df.columns

Index(['age_upon_outcome', 'animal_id_outcome', 'date_of_birth',
       'outcome_subtype', 'outcome_type', 'sex_upon_outcome',
       'age_upon_outcome_(days)', 'age_upon_outcome_(years)',
       'age_upon_outcome_age_group', 'outcome_datetime', 'outcome_month',
       'outcome_year', 'outcome_monthyear', 'outcome_weekday', 'outcome_hour',
       'outcome_number', 'dob_year', 'dob_month', 'dob_monthyear',
       'age_upon_intake', 'animal_id_intake', 'animal_type', 'breed', 'color',
       'found_location', 'intake_condition', 'intake_type', 'sex_upon_intake',
       'count', 'age_upon_intake_(days)', 'age_upon_intake_(years)',
       'age_upon_intake_age_group', 'intake_datetime', 'intake_month',
       'intake_year', 'intake_monthyear', 'intake_weekday', 'intake_hour',
       'intake_number', 'time_in_shelter', 'time_in_shelter_days'],
      dtype='object')

In [34]:
df["animal_type"].value_counts()

animal_type
Dog      45366
Cat      29539
Other     4428
Bird       339
Name: count, dtype: int64

In [35]:
mapping = {'Dog':1,'Cat':2, 'Other':3,'Bird':4,'Livestock':5,  
          }

df["animal_type"]= df['animal_type'].map(mapping)

In [36]:
#now for fuel_type
df["breed"].value_counts()

breed
Domestic Shorthair Mix      23423
Pit Bull Mix                 6256
Chihuahua Shorthair Mix      4831
Labrador Retriever Mix       4789
Domestic Medium Hair Mix     2326
                            ...
American                        1
Belgian Hare                    1
Rottweiler/Boxer                1
Plott Hound/Beagle              1
Britannia Petit Mix             1
Name: count, Length: 2155, dtype: int64

In [37]:
mapping1 = {
            'Domestic Shorthair Mix ':0,
            'Pit Bull Mix':1,
            'Chihuahua Shorthair Mix':2,
            'Labrador Retriever Mix':3,
            'Domestic Medium Hair Mix':4
        }
df["breed"]=df["breed"].map(mapping1)

In [38]:
df["color"].value_counts()

color
Black/White              8270
Black                    6673
Brown Tabby              4471
Brown                    3598
White                    2835
                         ...
Blue Tick/Tricolor          1
Green/Red                   1
Cream/Brown Merle           1
Red Merle/Brown Merle       1
Blue Smoke/Gray             1
Name: count, Length: 529, dtype: int64

In [39]:
mapping2 = {
            'Black/White  ':0,
            'Black':1,
            'Brown Tabby':2,
            'Brown ':3,
            'White':4
        }
df["color"]=df["color"].map(mapping2)

In [40]:
df["sex_upon_intake"].value_counts()

sex_upon_intake
Intact Male      25317
Intact Female    23704
Neutered Male    12708
Spayed Female    11153
Unknown           6789
Name: count, dtype: int64

In [41]:
mapping3 = {
            'Intact Male':0,
            'Intact Female ':1,
            'Neutered Male':2,
            'Spayed Female ':3,
            'Unknown':4
        }
df["sex_upon_intake"]=df["sex_upon_intake"].map(mapping3)

In [42]:
df["intake_type"].value_counts()

intake_type
Stray                 55935
Owner Surrender       15028
Public Assist          4994
Wildlife               3464
Euthanasia Request      251
Name: count, dtype: int64

In [43]:
mapping4 = {
            'Stray ':0,
            'Owner Surrender ':1,
            'Public Assist':2,
            'Wildlife  ':3,
            'Euthanasia Request':4
        }
df["intake_type"]=df["intake_type"].map(mapping4)

In [44]:
df["intake_condition"].value_counts()

intake_condition
Normal      70056
Injured      3997
Sick         3099
Nursing      1915
Aged          319
Other         147
Feral          92
Pregnant       47
Name: count, dtype: int64

In [45]:
mapping5 = {
            'Normal  ':0,
            'Injured  ':1,
            'Sick':2,
            'Aged':3,
            'Feral':2,
            'Pregnant':3,
            'Other':4
        }
df["intake_condition"]=df["intake_condition"].map(mapping5)

In [46]:
import pandas as pd

def convert_age_to_days(age):
    if pd.isnull(age):
        return None
    
    value, unit = age.split()
    value = int(value)
    
    if 'year' in unit:
        return value * 365
    elif 'month' in unit:
        return value * 30
    elif 'week' in unit:
        return value * 7
    elif 'day' in unit:
        return value
    else:
        return None

# Apply conversion
df['age_in_days'] = df['age_upon_intake'].apply(convert_age_to_days)

In [47]:
df.head()

,age_upon_outcome,animal_id_outcome,date_of_birth,outcome_subtype,outcome_type,sex_upon_outcome,age_upon_outcome_(days),age_upon_outcome_(years),age_upon_outcome_age_group,outcome_datetime,...,intake_datetime,intake_month,intake_year,intake_monthyear,intake_weekday,intake_hour,intake_number,time_in_shelter,time_in_shelter_days,age_in_days
0,10 years,A006100,2007-07-09 00:00:00,NaN,Return to Owner,Neutered Male,3650,10.0,"(7.5, 10.0]",2017-12-07 14:07:00,...,2017-12-07 00:00:00,12,2017,2017-12,Thursday,14,1.0,0 days 14:07:00.000000000,0.588194,3650
1,7 years,A006100,2007-07-09 00:00:00,NaN,Return to Owner,Neutered Male,2555,7.0,"(5.0, 7.5]",2014-12-20 16:35:00,...,2014-12-19 10:21:00,12,2014,2014-12,Friday,10,2.0,1 days 06:14:00.000000000,1.259722,2555
2,6 years,A006100,2007-07-09 00:00:00,NaN,Return to Owner,Neutered Male,2190,6.0,"(5.0, 7.5]",2014-03-08 17:10:00,...,2014-03-07 14:26:00,3,2014,2014-03,Friday,14,3.0,1 days 02:44:00.000000000,1.113889,2190
3,10 years,A047759,2004-04-02 00:00:00,Partner,Transfer,Neutered Male,3650,10.0,"(7.5, 10.0]",2014-04-07 15:12:00,...,2014-04-02 15:55:00,4,2014,2014-04,Wednesday,15,1.0,4 days 23:17:00.000000000,4.970139,3650
4,16 years,A134067,1997-10-16 00:00:00,NaN,Return to Owner,Neutered Male,5840,16.0,"(15.0, 17.5]",2013-11-16 11:54:00,...,2013-11-16 09:02:00,11,2013,2013-11,Saturday,9,1.0,0 days 02:52:00.000000000,0.119444,5840

In [48]:
features = [
    'animal_type',
    'sex_upon_intake',
    'age_in_days',
    'intake_type',
    'intake_condition'
]

X = df[features]
y = df['outcome_type']

In [49]:
#handling missing values
import numpy as np

X = df[features].copy()

# Numeric
X['age_in_days'] = X['age_in_days'].fillna(X['age_in_days'].median())

# Categorical
for col in ['animal_type', 'sex_upon_intake', 'intake_type', 'intake_condition']:
    X[col] = X[col].fillna('Unknown')

y = df['outcome_type'].copy()
y = y.fillna('Unknown')

In [50]:
#encoding part
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_cols = ['animal_type', 'sex_upon_intake', 'intake_type', 'intake_condition']
numeric_cols = ['age_in_days']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols),
        ('num', 'passthrough', numeric_cols)
    ]
)

In [51]:
#classification
X = df[features].copy()

# Fix categorical columns
categorical_cols = ['animal_type', 'sex_upon_intake', 'intake_type', 'intake_condition']

for col in categorical_cols:
    X[col] = X[col].astype(str)
    X[col] = X[col].fillna('Unknown')

# Fix numeric
X['age_in_days'] = pd.to_numeric(X['age_in_days'], errors='coerce')
X['age_in_days'] = X['age_in_days'].fillna(X['age_in_days'].median())

In [52]:


from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
import pandas as pd

X = df[features].copy()

categorical_cols = ['animal_type', 'sex_upon_intake', 'intake_type', 'intake_condition']

for col in categorical_cols:
    X[col] = X[col].fillna('Unknown')
    X[col] = X[col].astype(str)


X['age_in_days'] = pd.to_numeric(X['age_in_days'], errors='coerce')
X['age_in_days'] = X['age_in_days'].fillna(X['age_in_days'].median())

X = X.fillna('Unknown')

# Spliting again
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Fit model
model.fit(X_train, y_train)

# Predicting
y_pred = model.predict(X_test)

# Evaluating
print("Accuracy:", model.score(X_test, y_test))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Accuracy: 0.5833699403828051

Classification Report:

C:\Users\Rashita\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Rashita\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

                 precision    recall  f1-score   support

       Adoption       0.56      0.77      0.65      6638
           Died       0.00      0.00      0.00       153
       Disposal       0.00      0.00      0.00        67
     Euthanasia       0.75      0.54      0.63      1201
        Missing       0.00      0.00      0.00        15
Return to Owner       0.54      0.49      0.51      2985
      Rto-Adopt       0.00      0.00      0.00        34
       Transfer       0.63      0.43      0.52      4839
        Unknown       0.00      0.00      0.00         3

       accuracy                           0.58     15935
      macro avg       0.28      0.25      0.26     15935
   weighted avg       0.58      0.58      0.57     15935

C:\Users\Rashita\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [53]:
import pickle
pickle.dump(model,open('final_model.pkl','wb'))